### ISSUE TITLE
Possibility of lost commits where the same repository is added twice

### ISSUE THREAD

**Issue by louisq** [louisq/CAS_CodeRepoAnalyzer#3]
Given that the commit table only as a primary key on the commit hash and that CAS_CodeRepoAnalyzer performs upsert (sqlalchemy merge) on the commits of a repository the addition of the same repository to commitguru multiple times would result that the commits would not be assigned to the originating repository_id. They would instead be replaced and would point to the latest version of the repository which as been analysed by commitguru.

This will be addressed by adding a combined primary key on the repository_id and commit_hash which will make commits unique to each repository

**Comment by louisq** [comment]
Completed as discussed in the description

**Comment by xsultan** [comment]
Good catch. Great solution and a quick fix. Make sure you alter the table form your end.
